[  0] = {3, "read", "int fd", "void *buf", "size_t count"},
[  1] = {3, "write", "int fd", "void *buf", "size_t count"},
[  2] = {3, "open", "char *pathname", "int flags", "mode_t mode"},
[  3] = {1, "close", "int fd"},
[  9] = {6, "mmap", "void *addr", "size_t lenght", "int prot", "int flags", "int fd", "off_t offset"},
[ 20] = {3, "writev", "int fd", "iovec *iov", "int count"},
[ 40] = {4, "sendfile", "int ofd", "int ifd", "off_t *ofs", "size_t count"},
[335] = {0, "endsyscall"},
